# Generated by Django 3.1.5 on 2021-03-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('AddressLine1', models.CharField(max_length=50)),
                ('AddressLine2', models.CharField(blank=True, max_length=50, null=True)),
                ('TownCity', models.CharField(max_length=50)),
                ('County', models.CharField(max_length=50)),
                ('EirCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductCode', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10000)),
                ('Category', models.CharField(default='Select Category', max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('ProductDescription', models.TextField(blank=True, max_length=250)),
                ('Quantity', models.IntegerField(default=0)),
                ('EntryDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('LastUpdate', models.DateTimeField(auto_now=True, null=True)),
                ('Weight', models.DecimalField(decimal_places=1, default=0, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShopName', models.CharField(max_length=50)),
                ('Slogan', models.CharField(blank=True, max_length=150, null=True)),
                ('Description', models.TextField(max_length=500)),
                ('Logo', models.ImageField(null=True, upload_to='Logos/')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='Images/')),
                ('PhoneNo', models.IntegerField(default=0)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
