# Generated by Django 3.1.7 on 2021-03-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='Address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
