# Generated by Django 3.1.7 on 2021-03-10 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Address',
        ),
        migrations.AddField(
            model_name='product',
            name='Shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
    ]
