# Generated by Django 3.1.7 on 2021-03-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210310_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='id',
        ),
        migrations.AddField(
            model_name='shop',
            name='BusinessReg',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
