# Generated by Django 3.1.7 on 2021-03-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210310_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Shop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.shop'),
        ),
    ]
