# Generated by Django 3.1.7 on 2021-03-10 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210310_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='Address',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
