# Generated by Django 3.1.7 on 2021-03-10 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210310_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Shop',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='app.shop'),
        ),
    ]
