# Generated by Django 3.1.7 on 2021-04-01 20:44

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210401_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_image',
            field=models.ImageField(blank=True, default='', upload_to=app.models.upload_path),
        ),
    ]
