# Generated by Django 3.1.7 on 2021-04-01 20:48

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210401_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='', upload_to=app.models.upload_path),
        ),
    ]
