# Generated by Django 3.1.7 on 2021-04-05 18:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210401_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, default='', upload_to=app.models.upload_path),
        ),
    ]
