# Generated by Django 3.1.7 on 2021-04-07 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='app.shop'),
        ),
    ]
