# Generated by Django 3.1.7 on 2021-04-17 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210407_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('Yellow', 'Yellow'), ('White', 'White'), ('Black', 'Black'), ('Navy', 'Navy'), ('Brown', 'Brown'), ('Purple', 'Purple'), ('Pink', 'Pink')], default='Black', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out Of Stock', 'Out Of Stock')], default='In Stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food & Beverages', 'Food & Beverages'), ('Clothing & Accessories', 'Clothing & Accessories'), ('Home & Garden', 'Home & Garden'), ('Health & Beauty', 'Health & Beauty'), ('Sports & Leisure', 'Sports & Leisure'), ('Electronics & Computing', 'Electronics & Computing'), ('Books, DVD & CD', 'Books, DVD & CD'), ('Arts & Crafts', 'Arts & Crafts')], default='Food & Beverages', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
